# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-24 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lnktourl',
            name='shortcode',
            field=models.CharField(default='lnktodefaultshortcode', max_length=15),
            preserve_default=False,
        ),
    ]
