# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-24 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20171023_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='lnktourl',
            name='timestampo',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lnktourl',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
