# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-25 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20171023_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='lnktourl',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lnktourl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
